name: notion-backup-build-deploy

on:
  push:
    branches: [ master ]

  workflow_dispatch:

# Share data between jobs: actions/upload-artifact, actions/download-artifact

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Temporarily save jar artifact
        uses: actions/upload-artifact@v3
        with:
          name: notion-backup-jar
          path: ./target/notion-backup-1.0-SNAPSHOT.jar
          retention-days: 1

  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: build-jar
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          name: notion-backup-jar
          path: ./notion-backup-1.0-SNAPSHOT.jar
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jckleiner/notion-backup:latest
          build-args: |
            PATH_TO_JAR=./notion-backup-1.0-SNAPSHOT.jar

