name: notion-backup-build-deploy

on:
  push:
    branches: [ master ]

  # adds a "run workflow" button to the page
  workflow_dispatch:

# Share data between jobs: actions/upload-artifact, actions/download-artifact

jobs:
  build-deploy-jar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build with Maven
        run: mvn -B package --file pom.xml --no-transfer-progress

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: jckleiner/notion-backup:latest
          build-args: |
            PATH_TO_JAR=./target/notion-backup-1.0-SNAPSHOT.jar

