# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: notion-backup-workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '5 4 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Start Notion Backup
      run: java -jar ./target/notion-backup-1.0-SNAPSHOT.jar
      env:
        NOTION_LOCALE: en
        NOTION_TIMEZONE: 'Europe/Berlin'
        NOTION_SPACE_ID: ${{ secrets.NOTION_SPACE_ID }}
        NOTION_EMAIL: ${{ secrets.NOTION_EMAIL }}
        NOTION_PASSWORD: ${{ secrets.NOTION_PASSWORD }}
        #GDRIVE_ROOT_FOLDER_ID: ${{ secrets.GDRIVE_ROOT_FOLDER_ID }}
        #GDRIVE_SERVICE_ACCOUNT: ${{ secrets.GDRIVE_SERVICE_ACCOUNT }}
